DROP DATABASE IF EXISTS sp;
CREATE DATABASE sp CHARSET=utf8;

USE sp;

DROP TABLE IF EXISTS sp_user;
CREATE TABLE sp_user(
    uid INT(11) PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(32) NOT NULL ,
    upwd VARCHAR(32) NOT NULL,
    email VARCHAR(64) DEFAULT NULL,
    phone BIGINT(16) DEFAULT NULL,
    user_name VARCHAR(32) DEFAULT NULL,
    gender INT(11) DEFAULT NULL
);